### ISSUE TITLE
Remove Odin Inspector

### ISSUE THREAD

**Issue by beardordie** [DapperDino/Hel-RPG#1]
I'm an avid Odin Inspector user and love that you're using it in this project, but it should be removed from your repo. Thanks.

**Comment by DapperDino** [comment]
Thanks for pointing that out :) I'll quickly add it to my .gitignore :D

**Comment by DapperDino** [comment]
@beardordie I'm 99% sure I've done it now so feel free to check whether you still have access just to make sure. Thanks for the heads up.

**Comment by beardordie** [comment]
Yes. Thanks. And doing a video or part of a video on how you use Odin would be nice. :)
